// 导入统一常量
import { SYSTEM_CONSTANTS } from '@/constants';

export default {
  BASE_URL: import.meta.env.VITE_API_BASE_URL,
  PAGE_SIZE: SYSTEM_CONSTANTS.PAGE_SIZE,
  LOGIN_PATH: SYSTEM_CONSTANTS.LOGIN_PATH,
  TOKEN_NAME: SYSTEM_CONSTANTS.TOKEN_NAME,
  TOKEN_PREFIX: SYSTEM_CONSTANTS.TOKEN_PREFIX, // Token 前缀（注意空格）
  USER_INFO_KEY: SYSTEM_CONSTANTS.USER_INFO_KEY,
  REQUEST_TIMEOUT: SYSTEM_CONSTANTS.REQUEST_TIMEOUT, // 默认请求超时时间
  USER_INFO_FETCH_TIMEOUT: SYSTEM_CONSTANTS.USER_INFO_FETCH_TIMEOUT, // 获取用户信息超时时间
}
